name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.pkg }} @ ${{ matrix.system.nix }}
    runs-on: ${{ matrix.system.runner }}
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - vitejs
          - oxlint
          - oxfmt
          - rolldown
          - viteplus
          - default
        system:
          - { nix: x86_64-linux, runner: ubuntu-latest }
          - { nix: aarch64-linux, runner: ubuntu-24.04-arm }
          - { nix: aarch64-darwin, runner: macos-latest }

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v16

      - name: Setup Attic
        run: |
          nix profile install 'nixpkgs#attic-client'
          attic login central ${{ secrets.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
          attic use central:${{ secrets.ATTIC_CACHE }}

      - name: Build ${{ matrix.pkg }}
        run: nix build .#${{ matrix.pkg }} -L

      - name: Cache ${{ matrix.pkg }}
        run: |
          attic push central:${{ secrets.ATTIC_CACHE }} ./result;
