name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: ${{ matrix.pkg }} @ ${{ matrix.system.nix }}
    runs-on: ${{ matrix.system.runner }}
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - default
        system:
          - { nix: x86_64-linux, runner: ubuntu-latest }
          - { nix: aarch64-linux, runner: ubuntu-24.04-arm }
          - { nix: aarch64-darwin, runner: macos-latest }

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v16

      - name: Setup Attic
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          retry_wait_seconds: 30
          timeout_minutes: 10
          command: |
            nix profile install 'nixpkgs#attic-client'
            attic login central ${{ secrets.ATTIC_ENDPOINT }} ${{ secrets.ATTIC_TOKEN }}
            attic use central:${{ secrets.ATTIC_CACHE }}

      - name: Build & push uncached packages
        run: |
          nix profile install 'nixpkgs#nix-fast-build'
          nix-fast-build \
            --flake ".#packages.${{ matrix.system.nix }}" \
            --skip-cached \
            --no-nom \
            --no-link \
            --retries 3 \
            --attic-cache "central:${{ secrets.ATTIC_CACHE }}"
